# Intro Pandas
Autor: Leon Gjinovci

Pandas ist die wichtigste Python-Bibliothek für die Arbeit mit tabellarischen Daten (ähnlich wie Excel-Tabellen oder SQL-Datenbanken). 

Grundfunktionen von Python sind:
1. Datenstrukturen: `Series` und `DataFrame`
2. Daten inspizieren: Überblick über große Tabellen gewinnen
3. Auswahl & Filterung: Gezielt auf Zeilen und Spalten zugreifen
4. Datenmanipulation: Neue Spalten berechnen und fehlende Werte (`NaN`) bereinigen
5. Gruppierung & Aggregation: Daten zusammenfassen und auswerten

## Pandas und NumPy importieren

In [1]:
import numpy as np
import pandas as pd

print(f"Verwendete Pandas-Version: {pd.__version__}")

Verwendete Pandas-Version: 2.2.3

## Series und DataFrame

Pandas baut auf zwei zentralen Objekten auf:
* `Series` (1D): Eine einzelne Spalte mit einem Index (vergleichbar mit einer typisierten Liste oder einem eindimensionalen Array).
* `DataFrame` (2D): Eine vollständige Tabelle aus Zeilen und Spalten, wobei jede Spalte eine `Series` ist.

In [2]:
# 1. Eine einfache Series erstellen
umsatz_quartal = pd.Series(
    [12500, 15800, 14200, 19100], index=["Q1", "Q2", "Q3", "Q4"]
)
print("--- Pandas Series ---")
print(umsatz_quartal)
print("\nWert für Q2:", umsatz_quartal["Q2"])

--- Pandas Series ---
Q1    12500
Q2    15800
Q3    14200
Q4    19100
dtype: int64

Wert für Q2: 15800

In [3]:
# 2. Einen DataFrame aus einem Python-Dictionary erstellen
daten = {
    "Mitarbeiter": ["Anna", "Ben", "Clara", "David", "Elena", "Felix"],
    "Abteilung": ["IT", "Vertrieb", "IT", "Marketing", "Vertrieb", "IT"],
    "Alter": [28, 34, 41, 25, 38, 31],
    "Gehalt": [62000, 58000, 75000, 49000, 64000, np.nan],  # np.nan = fehlender Wert
    "Homeoffice_Tage": [3, 1, 4, 2, 1, 5],
}

df = pd.DataFrame(daten)
df  # "Magic Command": In Jupyter gibt die letzte Zeile einer Zelle die Tabelle formatiert aus --> sollte bereits bekannt sein!

  Mitarbeiter  Abteilung  Alter   Gehalt  Homeoffice_Tage
0        Anna         IT     28  62000.0                3
1         Ben   Vertrieb     34  58000.0                1
2       Clara         IT     41  75000.0                4
3       David  Marketing     25  49000.0                2
4       Elena   Vertrieb     38  64000.0                1
5       Felix         IT     31      NaN                5

## Daten inspizieren und verstehen

Wenn man reale Datensätze (z. B. über `pd.read_csv('datei.csv')`) lädt, verschafft man sich zuerst einen schnellen Überblick über Struktur, Datentypen und statistische Kennzahlen:
* `df.head(n)` / `df.tail(n)`: Zeigt die ersten bzw. letzten $n$ Zeilen.
* `df.info()`: Zeigt Datentypen, Speicherverbrauch und fehlende Werte.
* `df.describe()`: Berechnet statistische Kennzahlen (Mittelwert, Standardabweichung, Quartile) für alle numerischen Spalten.

In [4]:
print("--- Erste 3 Zeilen ---")
display(df.head(3))

print("\n--- Struktur & Datentypen ---")
df.info()

print("\n--- Statistische Zusammenfassung ---")
display(df.describe())

--- Erste 3 Zeilen ---

  Mitarbeiter Abteilung  Alter   Gehalt  Homeoffice_Tage
0        Anna        IT     28  62000.0                3
1         Ben  Vertrieb     34  58000.0                1
2       Clara        IT     41  75000.0                4

--- Struktur & Datentypen ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Mitarbeiter      6 non-null      object
 1   Abteilung        6 non-null      object
 2   Alter            6 non-null      int64
 3   Gehalt           5 non-null      float64
 4   Homeoffice_Tage  6 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 372.0+ bytes

--- Statistische Zusammenfassung ---

           Alter        Gehalt  Homeoffice_Tage
count   6.000000      5.000000         6.000000
mean   32.833333  61600.000000         2.666667
std     6.047038   9449.867724         1.632993
min    25.000000  49000.000000         1.000000
25%    28.750000  58000.000000         1.250000
50%    32.500000  62000.000000         2.500000
75%    37.000000  64000.000000         3.750000
max    41.000000  75000.000000         5.000000

## Daten auswählen und filtern (loc, iloc & Bedingungen)

Für den Zugriff auf Daten gibt es in Pandas drei primäre Wege:
1. Spaltenauswahl: Über den Spaltennamen in eckigen Klammern `df['Spalte']` oder `df[['Spalte1', 'Spalte2']]`.
2. `.loc[Zeilenname, Spaltenname]`: Auswahl über Labels/Namen (inklusive logischer Filter).
3. `.iloc[Zeilenposition, Spaltenposition]`: Auswahl streng über den numerischen Index (wie bei Python-Listen, beginnend bei `0`).

In [5]:
# Einzelne Spalte (gibt eine Series zurück) vs. mehrere Spalten (gibt einen DataFrame zurück)
namen = df["Mitarbeiter"]
teil_tabelle = df[["Mitarbeiter", "Gehalt"]]

# Auswahl mit .iloc (Zeile 0 bis 2, Spalte 0 bis 2)
print("--- Auswahl per Position (.iloc) ---")
display(df.iloc[0:3, 0:2])

# Auswahl mit .loc (Zeile mit Index 2, Spalten 'Mitarbeiter' und 'Abteilung')
print("--- Auswahl per Label (.loc) ---")
print(df.loc[2, ["Mitarbeiter", "Abteilung"]])

--- Auswahl per Position (.iloc) ---

  Mitarbeiter Abteilung
0        Anna        IT
1         Ben  Vertrieb
2       Clara        IT

--- Auswahl per Label (.loc) ---
Mitarbeiter    Clara
Abteilung         IT
Name: 2, dtype: object

In [6]:
# Logisches Filtern (Boolean Indexing)
# Finde alle Mitarbeiter aus der IT, die älter als 30 sind
it_erfahren = df[(df["Abteilung"] == "IT") & (df["Alter"] > 30)]

print("--- Gefilterte Daten (IT & Alter > 30) ---")
display(it_erfahren)

--- Gefilterte Daten (IT & Alter > 30) ---

  Mitarbeiter Abteilung  Alter   Gehalt  Homeoffice_Tage
2       Clara        IT     41  75000.0                4
5       Felix        IT     31      NaN                5

## Daten bereinigen und transformieren

In der Praxis sind Daten selten perfekt. Oft fehlen Werte (`NaN` = *Not a Number*) oder wir müssen aus bestehenden Spalten neue Kennzahlen berechnen.
* `df.isna().sum()`: Zählt fehlende Werte pro Spalte.
* `df.fillna(wert)`: Ersetzt fehlende Werte (z. B. durch den Mittelwert oder `0`).
* `df.dropna()`: Entfernt Zeilen mit fehlenden Werten komplett.

In [7]:
# 1. Fehlende Werte prüfen
print("Fehlende Werte pro Spalte:\n", df.isna().sum())

# 2. Fehlende Gehälter durch das Durchschnittsgehalt auffüllen
durchschnitts_gehalt = df["Gehalt"].mean()
df["Gehalt"] = df["Gehalt"].fillna(durchschnitts_gehalt)

# 3. Neue Spalte berechnen (Monatsgehalt & Bonus-Kategorie)
df["Monatsgehalt_Brutto"] = (df["Gehalt"] / 12).round(2)
df["Viel_Homeoffice"] = df["Homeoffice_Tage"] >= 3

display(df)

Fehlende Werte pro Spalte:
 Mitarbeiter        0
Abteilung          0
Alter              0
Gehalt             1
Homeoffice_Tage    0
dtype: int64

,Mitarbeiter,Abteilung,Alter,Gehalt,Homeoffice_Tage,Monatsgehalt_Brutto,Viel_Homeoffice
0,Anna,IT,28,62000.0,3,5166.67,True
1,Ben,Vertrieb,34,58000.0,1,4833.33,False
2,Clara,IT,41,75000.0,4,6250.00,True
3,David,Marketing,25,49000.0,2,4083.33,False
4,Elena,Vertrieb,38,64000.0,1,5333.33,False
5,Felix,IT,31,61600.0,5,5133.33,True

## Gruppieren, Aggregieren und Sortieren (groupby)

Mit `groupby()` lassen sich Daten nach Kategorien zusammenfassen (das Split-Apply-Combine-Prinzip, bekannt aus SQL oder Excel-Pivot-Tabellen). Zudem können Tabellen mit `sort_values()` beliebig sortiert werden.

In [8]:
# Durchschnittsgehalt und Durchschnittsalter pro Abteilung berechnen
abteilungs_statistik = (
    df.groupby("Abteilung")[["Gehalt", "Alter"]].mean().round(1)
)
print("--- Durchschnittswerte pro Abteilung ---")
display(abteilungs_statistik)

# Mehrere Aggregationen gleichzeitig mit .agg()
detaillierte_übersicht = df.groupby("Abteilung").agg(
    Anzahl_Mitarbeiter=("Mitarbeiter", "count"),
    Max_Gehalt=("Gehalt", "max"),
    Schnitt_Homeoffice=("Homeoffice_Tage", "mean"),
)
print("\n--- Detaillierte Abteilungs-Aggregation ---")
display(detaillierte_übersicht)

# Tabelle absteigend nach Gehalt sortieren
df_sortiert = df.sort_values(by="Gehalt", ascending=False)
print("\n--- Sortiert nach Gehalt (absteigend) ---")
display(df_sortiert)

--- Durchschnittswerte pro Abteilung ---

            Gehalt  Alter
Abteilung
IT         66200.0   33.3
Marketing  49000.0   25.0
Vertrieb   61000.0   36.0

--- Detaillierte Abteilungs-Aggregation ---

           Anzahl_Mitarbeiter  Max_Gehalt  Schnitt_Homeoffice
Abteilung
IT                          3     75000.0                 4.0
Marketing                   1     49000.0                 2.0
Vertrieb                    2     64000.0                 1.0

--- Sortiert nach Gehalt (absteigend) ---

,Mitarbeiter,Abteilung,Alter,Gehalt,Homeoffice_Tage,Monatsgehalt_Brutto,Viel_Homeoffice
2,Clara,IT,41,75000.0,4,6250.00,True
4,Elena,Vertrieb,38,64000.0,1,5333.33,False
0,Anna,IT,28,62000.0,3,5166.67,True
5,Felix,IT,31,61600.0,5,5133.33,True
1,Ben,Vertrieb,34,58000.0,1,4833.33,False
3,David,Marketing,25,49000.0,2,4083.33,False